services:
  # 1. Base de Datos
  postgres:
    image: postgres:16
    container_name: erp_postgres
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password123
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U erp_user -d erp_db"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # 2. Administrador de DB (pgAdmin) - opcional
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: erp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@miempresa.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "8081:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  # 3. API Backend (FastAPI) - opcional
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: erp_api
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api:/app
    restart: unless-stopped

  # 4. Directus (Admin/CRUD/API)
  directus:
    image: directus/directus:10.11.0
    container_name: erp_directus
    environment:
      KEY: "cambia-esto-en-produccion"
      SECRET: "cambia-esto-en-produccion"
      ADMIN_EMAIL: "admin@miempresa.com"
      ADMIN_PASSWORD: "admin123"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_DATABASE: "erp_db"
      DB_USER: "erp_user"
      DB_PASSWORD: "erp_password123"
      DB_SEARCH_PATH: "array:public,sigco"
      STORAGE_LOCATIONS: "local"
      STORAGE_LOCAL_DRIVER: "local"
      STORAGE_LOCAL_ROOT: "/directus/uploads"
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "8055:8055"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./directus-data:/directus/database
      - ./directus-uploads:/directus/uploads
    restart: unless-stopped

  # 5. Metabase (BI/KPIs)
  metabase:
    image: metabase/metabase:v0.49.12
    container_name: erp_metabase
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
        MD_DB_FILE: /metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
    restart: unless-stopped

  # 6. Frontend Low-Code (Appsmith)
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: erp_appsmith
    ports:
      - "8080:80"   # Acceso web principal
      - "9001:9001" # Supervisor (opcional)
    volumes:
      - ./appsmith-stacks:/appsmith-stacks
    restart: unless-stopped
    # Appsmith usa la red default bridge para ver a 'postgres' por su nombre
